// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.8.0.0
//      SpecFlow Generator Version:3.8.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TPC_UPC.API.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.8.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("NotificationUserResultsOfTrainingUser", Description="\tA coordinator create a training for tutors (users), so a notification is send to" +
        " the tutor.", SourceFile="Features\\NotificationUserResultsOfTrainingUser.feature", SourceLine=0)]
    public partial class NotificationUserResultsOfTrainingUserFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "NotificationUserResultsOfTrainingUser.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "NotificationUserResultsOfTrainingUser", "\tA coordinator create a training for tutors (users), so a notification is send to" +
                    " the tutor.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CoordinatorCreateATrainingForTutorsAndTheSystemAutomaticallySendANotificationToThem(string trainingId, string firstTutorId, string firstTutorName, string notificationId, string notificationDescription, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("TrainingId", trainingId);
            argumentsOfScenario.Add("FirstTutorId", firstTutorId);
            argumentsOfScenario.Add("FirstTutorName", firstTutorName);
            argumentsOfScenario.Add("NotificationId", notificationId);
            argumentsOfScenario.Add("NotificationDescription", notificationDescription);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Coordinator create a training for tutors and the system automatically send a noti" +
                    "fication to them", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given(string.Format("a session of training is created {0}", trainingId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
 testRunner.When(string.Format("I add a tutor for the training ({0}, {1})", firstTutorId, firstTutorName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
 testRunner.Then(string.Format("the system send notification for each tutor selected ({0}, {1})", notificationId, notificationDescription), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Coordinator create a training for tutors and the system automatically send a noti" +
            "fication to them, 1", new string[] {
                "mytag"}, SourceLine=11)]
        public virtual void CoordinatorCreateATrainingForTutorsAndTheSystemAutomaticallySendANotificationToThem_1()
        {
#line 5
this.CoordinatorCreateATrainingForTutorsAndTheSystemAutomaticallySendANotificationToThem("1", "101", "Piero", "903", "Aviso enviado por el coordinador", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Coordinator create a training for tutors and the system automatically send a noti" +
            "fication to them, 2", new string[] {
                "mytag"}, SourceLine=11)]
        public virtual void CoordinatorCreateATrainingForTutorsAndTheSystemAutomaticallySendANotificationToThem_2()
        {
#line 5
this.CoordinatorCreateATrainingForTutorsAndTheSystemAutomaticallySendANotificationToThem("2", "101", "Piero", "903", "Aviso enviado por el coordinador", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Coordinator create a training for tutors and the system automatically send a noti" +
            "fication to them, 3", new string[] {
                "mytag"}, SourceLine=11)]
        public virtual void CoordinatorCreateATrainingForTutorsAndTheSystemAutomaticallySendANotificationToThem_3()
        {
#line 5
this.CoordinatorCreateATrainingForTutorsAndTheSystemAutomaticallySendANotificationToThem("3", "102", "Julian", "903", "Aviso enviado por el coordinador", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
